### ISSUE TITLE
pdf没有正确显示化学符号

### ISSUE THREAD

**Issue by Starovcomst** [Anyayay/Chemistry-Note#7]
**04 有机化学基础 / 06生物大分子.pdf** 化学方程式出现Latex命令,没有正确显示化学符号。

**Comment by Anyayay** [comment]
已经在最新的提交中修改，应该是typora的锅，不过我的pdf文件并不是即使更新的（~~就是懒~~ ，隔一段时间才统一导出一次），如果有条件建议自行下载markdown文件
